### ISSUE TITLE
Package structure is by function instead of feature

### ISSUE THREAD

**Issue by ndrone** [kaitannmatthey/task-manager-web#3]
By function placing all your controllers in one package, all repositories in another is an older way of grouping classes. A newer way is by feature so an example used be `com.taskmanager.status` and in this package you would see `StatusController`, `StatusRepository`, and `Status` this way when the developer is dealing with status they don't have to leave the package. This also helps when features get removed. This way you just have to delete the entire package. Instead of hunting for all the classes through out all the packages.

**Comment by kaitannmatthey** [comment]
Updated package structure.
