### ISSUE TITLE
Controllers using autowired

### ISSUE THREAD

**Issue by ndrone** [kaitannmatthey/task-manager-web#5]
As discussed earlier today the use of `@Autowired` can be evil if not used with caution. A better way is
```
       private final StatusRepository statusRepo;

	public StatusController(StatusRepository statusRepo) {
		Assert.notNull(statusRepo, "StatusRepository must not be null");
		this.statusRepo = statusRepo;
	}
```

Don't worry Spring knows how to handle this automagically :) If you want to find out more place a break point on `Assert.notNull(statusRepo, "StatusRepository must not be null");` Start up the application in debug mode, and take a look at the stack trace to see how they get started.

**Comment by kaitannmatthey** [comment]
Done!
